[theme]
primaryColor = "#4e73df"
backgroundColor = "#f8f9fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#5a5c69"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[global]
developmentMode = false 